[tool.poetry]
name = "botyo"
version = "0.1.0"
description = ""
authors = ["cacko <alex@cacko.net>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
redis = "^4.1.0"
dataclasses-json = "^0.5.6"
wikipedia = "^1.4.0"
multiavatar = "^1.0.3"
Pillow = "^9.0.0"
lxml = "^4.7.1"
Unidecode = "^1.3.2"
APScheduler = "^3.8.1"
stringcase = "^1.2.0"
emoji = {git = "https://github.com/carpedm20/emoji"}
CairoSVG = "^2.5.2"
emoji-country-flag = "^1.3.0"
toml = "^0.10.2"
jsonrpcclient = "^4.0.2"
rich = "^11.0.0"
requests-toolbelt = "^0.9.1"
nltk = "^3.6.7"
thefuzz = {extras = ["speedup"], version = "^0.19.0"}
random-user-agent = "^1.0.1"
validators = "^0.18.2"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pydebug = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
