# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - poetry run python -m app
    silent: true

  redis:
    desc: open redis-cli
    cmds:
      - redis-cli $REDIS_CLI%

  logs:
    desc: monitor logs
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;journalctl --user -u botyo -f' | ccze -A

  start:
    desc: start the service
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user start botyo'

  restart:
    desc: restart the service
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user restart botyo'

  stop:
    desc: stop the server
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user stop botyo'

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  2>&1 > /dev/null
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" 2>&1 > /dev/null
      - git push  2>&1 > /dev/null

  pull:
    desc: pulls from git
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd ~/botyo;git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  install:
    desc: calls poetry install and npm ci
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd ~/botyo;poetry install'

  deploy:
    desc: shortcut for stop -> push -> pull -> restart
    cmds:
      - task: stop
      - task: push
      - task: pull
      - task: install
      - task: restart

  run:
    desc: run the server
    cmds:
      - export PATH="/home/jago/.pyenv/plugins/pyenv-virtualenv/shims:/home/jago/.pyenv/shims:/home/jago/.pyenv/bin:/home/jago/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/games"
      - direnv exec . poetry run python -m app
