[redis]
url = "redis://192.168.0.106/5"

[signal]
groups = [
  "iUNWO08W125MQZhNappyeRyYnM5nubW47/Lw1j3nX8Q=",
  "9cC95M1QQANjS1IoIyIlB6dOSxq/A/PdgPuVeRu9yhU=",
]
host = "/Users/jago/signal.sock"

[znayko]
client = "BOTYO"
host = "127.0.0.1"
phone = "+447479303304"
port = 7777

[cachable]
path = "./cache"
